name: App or Dev Build and Deploy
on:
  push:
    branches: [main, dev, experimental]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20"
      - name: Install Dependencies
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install --no-optional
      - name: Run Tests
        run: npm test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20"
      - name: Install Dependencies
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install --no-optional
      - name: Build
        run: |
          if [ "${{ github.ref }}" == "refs/heads/dev" ] || [ "${{ github.ref }}" == "refs/heads/experimental" ]; then
            npm run build:dev
          else
            npm run build:prod
          fi
      - name: Set Target Directory
        run: |
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            echo "TARGET_DIR=/home/ec2-user/www-dev" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/experimental" ]; then
            echo "TARGET_DIR=/home/ec2-user/www-exp" >> $GITHUB_ENV
          else
            echo "TARGET_DIR=/home/ec2-user/www" >> $GITHUB_ENV
          fi
      - name: Deploy to Server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOYMENT_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan mytender.io >> ~/.ssh/known_hosts
          scp -i ~/.ssh/id_rsa -r ./dist/* ec2-user@mytender.io:$TARGET_DIR
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOYMENT_KEY }}
